export const patients = [
    {
        
      id: 1,
      name: "John Smith",
      age: 45,
      condition: "Hypertension",
      conditionIcon: "fas fa-heartbeat",
      conditionColor: "green",
      time: "2 days ago",
      img: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80",
    },
    {
      id: 2,
      name: "Emily Davis",
      age: 32,
      condition: "Diabetes",
      conditionIcon: "fas fa-syringe",
      conditionColor: "yellow",
      time: "1 week ago",
      img: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&w=400&q=80",
    },
    {
      id: 3,
      name: "Robert Johnson",
      age: 58,
      condition: "Heart Disease",
      conditionIcon: "fas fa-heart",
      conditionColor: "red",
      time: "3 days ago",
      img: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=400&q=80",
    },
    {
      id: 4,
      name: "Sarah Wilson",
      age: 29,
      condition: "Asthma",
      conditionIcon: "fas fa-lungs",
      conditionColor: "blue",
      time: "2 weeks ago",
      img: "https://images.unsplash.com/photo-1554151228-14d9def656e4?auto=format&fit=crop&w=400&q=80",
    },
    {
      id: 5,
      name: "Michael Brown",
      age: 50,
      condition: "Arthritis",
      conditionIcon: "fas fa-bone",
      conditionColor: "purple",
      time: "5 days ago",
      img: "https://images.unsplash.com/photo-1552058544-f2b08422138a?auto=format&fit=crop&w=400&q=80",
    },
  ];
  